

- name: copy mask_rcnn directory 
  copy: src=mask_rcnn dest=/home/wagner/Desktop 

- name: Check mask_rcnn.py
  stat: path=/home/wagner/Desktop/mask_rcnn/mask_rcnn.py
  register: mask_rcnn



- name: Object detection using mask_rcnn
  when: mask_rcnn.stat.exists == True
  script: /home/wagner/Desktop/mask_rcnn/mask_rcnn.py --image {{my_image}} --mask-rcnn mask-rcnn-coco 
  args:
   executable: python
   chdir: /home/wagner/Desktop/mask_rcnn

 

